# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 19:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import qrmaster.models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='id',
            field=models.CharField(default=qrmaster.models.pk_gen, max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quest',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
